create table short_url (
  id bigint generated by default as identity primary key,
  code varchar(16) not null unique,
  destination_url varchar(2048) not null,
  created_at timestamp with time zone not null,
  expires_at timestamp with time zone,
  status varchar(16) not null
);
create index idx_short_url_code_status on short_url (code, status);
create table click_aggregate (
  id bigint generated by default as identity primary key,
  short_url_id bigint not null,
  bucket_start timestamp with time zone not null,
  click_count bigint not null,
  constraint fk_click_aggregate_url foreign key (short_url_id) references short_url(id),
  constraint uk_click_aggregate_bucket unique (short_url_id, bucket_start)
);
